# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: mysql2
  encoding: utf8
  database: advokatgra48.ru
  pool: 2
  username: advokatgra48.ru
  password: K3cUZ566YPjnEUtY
test:
  adapter: mysql2
  encoding: utf8
  database: advokatgra48.ru
  pool: 2
  username: advokatgra48.ru
  password: K3cUZ566YPjnEUtY
production:
  adapter: mysql2
  encoding: utf8
  database: advokatgra48.ru
  pool: 2
  username: advokatgra48.ru
  password: K3cUZ566YPjnEUtY
  secret_key_base: <%= ENV["SECRET_KEY_ADVOKATGRA48RU"] %>